FROM apache/airflow:3.1.8

USER airflow

RUN pip install --no-cache-dir \
    duckdb \
    pandas \
    psycopg2-binary \
    python-dotenv \
    requests \
    dbt-core==1.10.* \
    dbt-postgres==1.10.*